#!/bin/bash
echo let's goooc: Nokuthula Chirwa's Personal Meeting Room

Join Zoom Meeting
https://us05web.zoom.us/j/7620703572?pwd=STZSM1VjbkNhZHhPdjFnQjJFRURZUT09

Meeting ID: 762 070 3572
Passcode: 14S7uf

!
